name: CI

on:
    workflow_dispatch:
    push:
        branches:
            - 'main'
        tags:
            - 'v*'
    pull_request:
        types: [opened, synchronize]
        branches:
            - 'main'

concurrency: ci-${{ github.ref_name }}

env:
    TERM: xterm-256color
    NODE_VERSION: 20
    PNPM_VERSION: 8
    COMMIT_SHA: ${{ github.event.pull_request.head.sha || github.sha }}
    BRANCH_OR_TAG: ${{ github.event.pull_request.head.ref || github.ref_name }}
    IS_MAIN: ${{ github.ref_name == 'main' }}
    IS_PULL_REQUEST: ${{ github.event_name == 'pull_request' }}

jobs:
    check:
        name: Check
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              timeout-minutes: 2

            - name: Set up pnpm
              uses: pnpm/action-setup@v2
              timeout-minutes: 2
              with:
                  version: ${{ env.PNPM_VERSION }}

            - name: Set up Node.js
              uses: actions/setup-node@v4
              timeout-minutes: 2
              with:
                  node-version: ${{ env.NODE_VERSION }}
                  cache: pnpm

            - name: Install npm dependencies
              timeout-minutes: 2
              run: |
                  make install-ci

            - name: Check TypeScript
              timeout-minutes: 2
              run: |
                  make typecheck

            - name: Bundle TypeScript
              timeout-minutes: 2
              run: |
                  make build

            - name: Run tests
              timeout-minutes: 2
              run: |
                  make test-ci

            - name: Check formatting
              timeout-minutes: 2
              run: |
                  make format-ci

            - name: Check lint errors
              timeout-minutes: 2
              run: |
                  make lint-ci
