name: CI

on:
    workflow_dispatch:
    push:
        branches:
            - 'main'
        tags:
            - 'v*'
    pull_request:
        types: [opened, synchronize]
        branches:
            - 'main'

concurrency: ci-${{ github.ref_name }}

env:
    TERM: xterm-256color
    COMMIT_SHA: ${{ github.event.pull_request.head.sha || github.sha }}
    BRANCH_OR_TAG: ${{ github.event.pull_request.head.ref || github.ref_name }}
    IS_MAIN: ${{ github.ref_name == 'main' }}
    IS_PULL_REQUEST: ${{ github.event_name == 'pull_request' }}

jobs:
    check:
        name: Check
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [22, 23, 24]
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              timeout-minutes: 2

            - name: Set up pnpm
              uses: pnpm/action-setup@v4
              timeout-minutes: 2

            - name: Set up Node.js
              uses: actions/setup-node@v4
              timeout-minutes: 2
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: pnpm

            - name: Install npm dependencies
              timeout-minutes: 2
              run: |
                  pnpm install --frozen-lockfile

            - name: Check TypeScript
              timeout-minutes: 2
              run: |
                  pnpm run typecheck

            - name: Bundle TypeScript
              timeout-minutes: 2
              run: |
                  pnpm run build:ci

            - name: Run tests
              timeout-minutes: 2
              run: |
                  pnpm run test:ci

            - name: Check formatting
              timeout-minutes: 2
              run: |
                  pnpm run format:ci

            - name: Check lint errors
              timeout-minutes: 2
              run: |
                  pnpm run lint:ci
